### PR TITLE
Added UI to edit flags, new API endpoint syntax, etc.

### PR DESCRIPTION
**Pull request by khoin**
Chris,

To check this PR, run `go run example.go` in `example/` like before.

Choose dummy > run > add in the web interface, you should see two input boxes to input number.
Clicking Execute and you would see the result. 

You should see `I'm always printed: <number>`. The "I'm always printed" part is from the root command persistent prerun. 

Changes since last PR:
* PreRun, PersistentPreRun, etc. are now working. (It turns out Cobra has a method to execute things properly)
* The API endpoint has now changed to what we've discussed last time. There's a brief explanation in README.md
* Non-persistent flags can now be edited in the web interface.

Questions:
* Right now, every time you click Execute to add two numbers, it makes a GET request to `//localhost:8080/dummy/run/add?num1=99&num2=1`, I think you might want something like: `//localhost:8080/<customString>/dummy/run/add?num1=99&num2=1`? Let me know.
* Flags are confusing to me. Would you want some of them to be non-modifiable to the users? I'm also guessing that PersistentFlags are implied by default?
For example, in `example/cmd.go`, we have persistent flags config and inBackground. I'm guessing that if someone runs `dummy run add --num1=1 --num2=9`, it is actually `dummy run add --config=./conf.toml --inBackground=false --num1=1 --num2=9`?  So somewhere down the line, I think you wouldn't want end-users to be able to change its config file or background. 

Let me know about the PR and also questions. 

Also, index.html in example/ isn't in .gitignore, it is basically just the output whenever you run the program. Do you want me to put that in .gitignore or not?

### CODE REVIEW

**Review by ctessum — APPROVED** [review]

**Comment by ctessum** [comment]
Great! To answer your questions:

* The GET address is fine as-is.
* I think we want all of the flags to be modifiable. The difference between persistent flags and non-persistent flags is that is that persistent flags are also passed to subcommands, whereas the non-persistent flags are only used if the command in question is the one that's actually running (not a parent of the running command). So to be consistent with this I think we always want the persistent flags to be visible and modifiable, but the non-persistent flags should only be visible when there isn't any subcommand selected. Let me know if that doesn't make sense.
* In InMAP and probably other programs, the config file and the command flags are closely interrelated using [this library](https://github.com/spf13/viper). I think the ideal behavior would be that changing the config file would update the default values of the flags, but this is not a priority for now. I don't have a strong sense of what it means to "run in the background" in this context.
* I think it's okay to keep index.html as part of the repository so it's clear when changes are made, but I don't have a strong preference.

Next steps:
* Make some changes to the code so that it more closely follows [best practices](https://goreportcard.com/report/github.com/ctessum/gobra).
* Start trying to get it to work with InMAP. The relevant code is [here](https://github.com/spatialmodel/inmap/blob/master/inmaputil/cmd.go). I think what we want is that if a user runs the root command (either by double-clicking on the executable or running `inmap` without any subcommands) that the Root command will start the server and open a browser window at the correct address.

Let me know if you have any questions.

**Comment by khoin** [comment]
Hi Chris,

I've aligned with the practices in the Go Report Card:
* I've run gofmt on the files that were listed
* I've run golint on the files that were listed
Is there a way to make Go Report Card do a scan on a branch? I want to have it scan on `khoin/gobra:branchname` before pulling a PR.

I will work on bridging between InMap and gobra. Even though I haven't successfully bridge these two yet, I'm thinking of something like this: 
```go
import "os/exec"

var Root = &cobra.Command {
    [...],
    Run: func(...) {
        //stuff
             gobraServer.Start(); // instantiate this object somewhere above
             exec.Command("chrome $path_to_exported_html") // I'm using Google Chrome in this case, and I'm assuming chrome is in the PATH.
        //stuff
   }
}
```
Perhaps this may be what you want.

**Comment by khoin** [comment]
Note: This is a comment on the previous PR. I'll file a PR (with the GoReport fixes) when I have Inmap working with gobra. 

I need to have Inmap running on my machine first before I can start working. I'll try to follow the instructions in the README.md. I think I might have to follow up with you on how to install it.

**Comment by ctessum** [comment]
> Is there a way to make Go Report Card do a scan on a branch?

I'm not sure, but you can run most of the checks in your text editor. For Atom, the package is [go-plus](https://atom.io/packages/go-plus). I think there are also extensions for most other editors. You can also add [travis](https://travis-ci.org/) hooks to run the individual checks, but adding the extensions to the text editor is probably most efficient.

> I'm thinking of something like this:

That is more or less what I had in mind. We will want to make sure that the browser-opening command works on all supported platforms, and one way to do that is to use a pre-existing package. Two that immediately show up are [here](https://github.com/skratchdot/open-golang) and [here](https://godoc.org/github.com/pkg/browser), but I don't know which if either of those is the best one.

> I need to have Inmap running on my machine first

Installing it should be as simple as `go get github.com/spatialmodel/inmap`. With the most recent commit you should be able to run it with `inmap run steady` and no other arguments, but let me know whether that actually works.

**Comment by ctessum** [comment]
Also, I'm leading a workshop/tutorial on InMAP here in China next tuesday (monday seattle time), so if it's feasible to get a GUI working in InMAP before then that would probably make the workshop go much more smoothly, but if not that is okay. I understand you have a lot of other commitments/classes/etc and are only supposed to be working a limited number of hours.

**Comment by khoin** [comment]
Here was my trial for today:
* Added GOPATH and GOROOT to PATH.
* Went and run `go get -u github.com/spatialmodel/inmap`
* `inmap run steady` did not work
* I navigated to `[...]/spatialmodel/inmap/inmap/` then do `go run main.go`. This worked.
* I tried running `go run main.go run steady`. It complains about not having `testEmis.shp` not existing. I checked in `./testdata` that it does exist by doing `cat ./testdata/testEmis.shp`.
* After a few tinkling, I figured it's because InMap looks at `/src/github.com/[...]` where as it should be `$GOPATH/src/github.com/[...]`. So I thought my $GOPATH, $GOROOT wasn't set up correctly. I was right. I set it up correctly now and it runs well(!). I figured it was because my other terminal has the PATHs set up correctly but I didn't include it in bash_rc. 

No work has been done to bridge gobra today but I'm confident that it'll happen tomorrow.

Also, I've just checked that even though the PATHs are set up correctly, I still cannot run "inmap run steady", let me know if this in an error on my end.

**Comment by ctessum** [comment]
Does the `inmap` executable exist in `$GOPATH/bin`?

Did you try `go get -u github.com/spatialmodel/inmap/...` (with the `...` part being key) or `go get -u github.com/spatialmodel/inmap/inmap` (with the second `inmap` being key) and then `inmap run steady`?

**Comment by khoin** [comment]
>Does the inmap executable exist in $GOPATH/bin?

I'm not at work computer anymore, but that might have been the case. It (`inmap run steady`) works now on my Windows machine, and I've added the correct paths.

However, if I run it barely, it complains: `InMAP: problem initializing model: there is not CTM data overlapping at least 90% of the InMAP cell at {X:-2.592e+06 Y:-1.944e+06}` 

So I have to pass in config file: `inmap run steady --config=[path_to_some_config].toml`

**Comment by khoin** [comment]
`go get -u github.com/spatialmodel/inmap/...` appears to work now (on work Mac). I now see the executable in `$GOPATH/bin`.

**Comment by khoin** [comment]
I've successfully linked Gobra with InMap. Changes in the next PR will both be in Gobra and InMap. 

Notes: Just like the CLI, I have to state "configExample.toml" to see the model running. Also, I can see **cobra** outputting to the web interface (e.g. help messages, etc.) but the model's output is still in the CLI. 

I'll make a PR now for you to see.

**Pull request merged**
